### ISSUE TITLE
Transactions (sending) on TestNet not working

### ISSUE THREAD

**Issue by a301b** [mmick66/jswallet#2]
I'm getting  the following error PropertyTypeError {message: "Expected property "1" of type Satoshi, got Number -869423492"

**Comment by ryuheimat** [comment]
Yes, I also get such error and according to my tracking result, I noticed that the `getFee()` function is incorrect.
For example, getFee() return 2828421897 and it means that the fee is more than 28 btc.
I think `block.fee` is total fee of all transactions in that block.

**Comment by mmick66** [comment]
I just added the calculation of fees taken from a [remote](https://bitcoinfees.earn.com/api) API. Let me know if you have problems with it. 

This is of course temporary.

**Comment by mmick66** [comment]
I recently [bumped](https://testnet.manu.backend.hamburg/faucet) into this message:

> Hey! I need to tell you this faucet is shut down for a while.
> 
> Right now there's a big tx flood going on on Bitcoin Testnet, so its nearly impossible to operate normally. Transactions are stuck, basically. And all our testnet wallets are also stuck, since every possible input is already used and locked in unconfirmed transactions.
> 
> The testnet community is trying to fix it, but this may take a while.
